In [1]:
import pandas as pd

In [16]:
#reading 1 csv file from the website
df_premier23 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/E0.csv')

In [ ]:
df_premier23

In [19]:
#Rename Columns
df_premier23.rename(columns={'FTHG' : 'Home_goals',
                             'FTAG': 'Away_goals'}, inplace=True)

In [24]:
# Show Data Frame
df_premier23

,Div,Date,Time,HomeTeam,AwayTeam,Home_goals,Away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,19/05/2024,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,...,2.78,-0.75,1.73,2.08,1.78,2.16,1.93,2.21,1.81,2.05
376,E0,19/05/2024,16:00,Liverpool,Wolves,2,0,H,2,0,...,5.17,-2.75,2.07,1.86,2.04,1.85,2.10,1.89,2.04,1.82
377,E0,19/05/2024,16:00,Luton,Fulham,2,4,A,1,2,...,2.69,0.25,2.00,1.93,1.99,1.93,2.02,1.94,1.96,1.91
378,E0,19/05/2024,16:00,Man City,West Ham,3,1,H,2,1,...,4.82,-3.00,2.03,1.90,1.99,1.90,2.05,1.99,1.96,1.91
379,E0,19/05/2024,16:00,Sheffield United,Tottenham,0,3,A,0,1,...,3.81,1.50,2.06,1.87,2.05,1.88,2.08,1.89,2.01,1.86

In [29]:
# Filter rows where Liverpool is either the home or away team
liverpool_stats = df_premier23[(df_premier23['HomeTeam'] == 'Liverpool') | (df_premier23['AwayTeam'] == 'Liverpool')]

# Display the filtered data
print(liverpool_stats)

    Div        Date   Time          HomeTeam          AwayTeam  Home_goals  \
8    E0  13/08/2023  16:30           Chelsea         Liverpool           1
12   E0  19/08/2023  15:00         Liverpool       Bournemouth           3
28   E0  27/08/2023  16:30         Newcastle         Liverpool           1
37   E0  03/09/2023  14:00         Liverpool       Aston Villa           3
39   E0  16/09/2023  12:30            Wolves         Liverpool           1
57   E0  24/09/2023  14:00         Liverpool          West Ham           3
66   E0  30/09/2023  17:30         Tottenham         Liverpool           2
76   E0  08/10/2023  14:00          Brighton         Liverpool           2
80   E0  21/10/2023  12:30         Liverpool           Everton           2
98   E0  29/10/2023  14:00         Liverpool     Nott'm Forest           3
108  E0  05/11/2023  16:30             Luton         Liverpool           1
117  E0  12/11/2023  14:00         Liverpool         Brentford           3
120  E0  25/11/2023  12:30          Man City         Liverpool           1
137  E0  03/12/2023  14:00         Liverpool            Fulham           4
145  E0  06/12/2023  19:30  Sheffield United         Liverpool           0
150  E0  09/12/2023  12:30    Crystal Palace         Liverpool           1
168  E0  17/12/2023  16:30         Liverpool        Man United           0
176  E0  23/12/2023  17:30         Liverpool           Arsenal           1
181  E0  26/12/2023  17:30           Burnley         Liverpool           0
196  E0  01/01/2024  20:00         Liverpool         Newcastle           4
206  E0  21/01/2024  16:30       Bournemouth         Liverpool           0
215  E0  31/01/2024  20:15         Liverpool           Chelsea           4
226  E0  04/02/2024  16:30           Arsenal         Liverpool           3
230  E0  10/02/2024  15:00         Liverpool           Burnley           3
238  E0  17/02/2024  12:30         Brentford         Liverpool           1
249  E0  21/02/2024  19:30         Liverpool             Luton           4
262  E0  02/03/2024  15:00     Nott'm Forest         Liverpool           0
276  E0  10/03/2024  15:45         Liverpool          Man City           1
291  E0  31/03/2024  14:00         Liverpool          Brighton           2
301  E0  04/04/2024  19:30         Liverpool  Sheffield United           3
310  E0  07/04/2024  15:30        Man United         Liverpool           2
319  E0  14/04/2024  14:00         Liverpool    Crystal Palace           0
329  E0  21/04/2024  16:30            Fulham         Liverpool           1
333  E0  24/04/2024  20:00           Everton         Liverpool           2
336  E0  27/04/2024  12:30          West Ham         Liverpool           2
355  E0  05/05/2024  16:30         Liverpool         Tottenham           4
366  E0  13/05/2024  20:00       Aston Villa         Liverpool           3
376  E0  19/05/2024  16:00         Liverpool            Wolves           2

     Away_goals FTR  HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  \
8             1   D     1     1  ...     2.52  0.25      1.98      1.92
12            1   H     2     1  ...     3.77 -2.00      1.86      2.07
28            2   A     1     0  ...     2.60 -0.25      1.95      1.98
37            0   H     2     0  ...     2.97 -1.00      2.05      1.88
39            3   A     1     0  ...     2.56  0.75      2.02      1.91
57            1   H     1     1  ...     3.11 -1.50      2.01      1.92
66            1   H     1     1  ...     3.07  0.25      1.92      2.01
76            2   D     1     2  ...     3.45  0.50      1.83      2.10
80            0   H     0     0  ...     2.94 -1.50      2.11      1.82
98            0   H     2     0  ...     2.79 -1.75      1.93      2.00
108           1   D     0     0  ...     3.22  2.00      2.00      1.93
117           0   H     1     0  ...     2.83 -1.50      2.05      1.85
120           1   D     1     0  ...     2.61 -0.75      1.88      2.05
137           3   H     2     2  ...     3.01 -1.75      1.97      1.96
145           2   A     0     1  ...     3.38  2.00      2.03      1.78
150           2   A     0     0  ...     2.25  1.00      2.07      1.83
168           0   D     0     0  ...     3.02 -1.50      1.90      2.03
176           1   D     1     1  ...     2.30  0.00      1.86      2.07
181           2   A     0     1  ...     2.72  1.50      1.84      2.09
196           2   H     0     0  ...     3.12 -1.50      2.01      1.92
206           4   A     0     0  ...     2.90  0.75      2.03      1.90
215           1   H     2     0  ...     2.68 -1.00      2.06      1.84
226           1   H     1     1  ...     2.20 -0.25      1.92      2.01
230           1   H     1     1  ...     3.47 -2.25      1.99      1.94
238           4   A     0     1  ...     2.78  1.00      1.75      2.05
249           1   H     0     1  ...     3.16 -1.75      2.01      1.89
262           1   A     0     0  ...     2.54  1.00      1.90      2.00
276           1   D     0     1  ...     2.71  0.50      1.86      2.07
291           1   H     1     1  ...     3.61 -1.75      2.02      1.91
301           1   H     1     0  ...     5.08 -3.00      1.87      2.03
310           2   D     0     1  ...     3.53  1.00      1.95      1.95
319           1   A     0     1  ...     3.56 -2.00      1.89      2.04
329           3   A     1     1  ...     2.77  0.75      2.07      1.86
333           0   H     1     0  ...     2.62  1.25      2.07      1.86
336           2   D     1     0  ...     3.14  1.00      2.05      1.85
355           2   H     2     0  ...     3.97 -1.50      2.00      1.80
366           3   D     1     2  ...     3.20  0.75      1.92      2.01
376           0   H     2     0  ...     5.17 -2.75      2.07      1.86

     PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
8     2.00   1.93     2.03     2.08     1.91     1.96
12    1.85   2.08     1.91     2.11     1.84     2.03
28    1.96   1.96     2.04     1.99     1.92     1.93
37    2.04   1.88     2.06     1.96     1.97     1.90
39    2.03   1.90     2.12     1.92     2.04     1.83
57    2.01   1.91     2.04     1.96     1.96     1.91
66    1.90   2.02     1.99     2.02     1.90     1.96
76    1.83   2.09     1.89     2.11     1.83     2.05
80    2.09   1.83     2.11     1.93     2.03     1.84
98    1.84   2.08     1.93     2.16     1.83     2.03
108   1.95   1.95     2.02     1.97     1.95     1.91
117   2.08   1.85     2.10     1.90     2.03     1.85
120   1.88   2.04     1.97     2.06     1.87     1.98
137   1.87   2.04     1.97     2.10     1.86     2.00
145   2.09   1.81     2.17     1.87     2.08     1.80
150   2.10   1.84     2.19     1.87     2.08     1.80
168   1.88   2.04     2.00     2.07     1.91     1.97
176   1.86   2.07     1.89     2.17     1.82     2.07
181   1.83   2.08     1.98     2.12     1.84     2.03
196   1.98   1.93     2.14     1.94     2.01     1.87
206   2.03   1.89     2.09     1.91     1.99     1.86
215   2.10   1.84     2.14     1.88     2.05     1.83
226   1.93   2.00     2.00     2.01     1.91     1.95
230   1.98   1.93     2.04     1.97     1.95     1.91
238   1.79   2.18     1.90     2.19     1.81     2.08
249   1.95   1.95     2.04     2.05     1.92     1.94
262   1.92   2.01     1.95     2.09     1.89     1.98
276   1.86   2.07     1.88     2.15     1.83     2.06
291   2.01   1.93     2.04     1.94     1.97     1.89
301   1.94   1.94     2.00     2.03     1.92     1.94
310   2.01   1.93     2.01     2.00     1.96     1.91
319   1.87   2.06     1.93     2.06     1.87     2.00
329   2.07   1.87     2.10     1.88     2.05     1.83
333   2.06   1.88     2.07     1.89     2.02     1.84
336   2.05   1.86     2.09     1.90     2.02     1.85
355   2.05   1.89     2.06     1.89     2.01     1.85
366   1.92   2.02     1.92     2.03     1.89     1.98
376   2.04   1.85     2.10     1.89     2.04     1.82

[38 rows x 106 columns]

In [31]:
# Calculates the total number of goals scored
# Total goals scored when Liverpool is the Home team
home_goals = liverpool_stats[liverpool_stats['HomeTeam'] == 'Liverpool']['Home_goals'].sum()

# Total goals scored when Liverpool is the Away team
away_goals = liverpool_stats[liverpool_stats['AwayTeam'] == 'Liverpool']['Away_goals'].sum()

# Total goals scored
total_goals_scored = home_goals + away_goals

print(f'Total Goals Scored: {total_goals_scored}')

Total Goals Scored: 86

In [33]:
# Filter for Liverpool matches
home_goals = liverpool_stats[liverpool_stats['HomeTeam'] == 'Liverpool']['Home_goals'].sum()
away_goals = liverpool_stats[liverpool_stats['AwayTeam'] == 'Liverpool']['Away_goals'].sum()

print(f'Home Goals: {home_goals}, Away Goals: {away_goals}')

Home Goals: 49, Away Goals: 37

In [28]:
# goals against
total_goals_against = liverpool_stats['Home_goals'][liverpool_stats['AwayTeam'] == 'Liverpool'].sum() + \
                      liverpool_stats['Away_goals'][liverpool_stats['HomeTeam'] == 'Liverpool'].sum()
print(f'Total Goals Against: {total_goals_against}')

Total Goals Against: 41